name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "25 04,09 * * *" # (UTC) 4:25 AM & 9:25 AM -> (NEP) 10:05 AM & 03:10 PM

permissions:
  contents: write

jobs:

  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: python src/csv_writer.py
    - name: Commit changes
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add .
        git commit -m "Update data" || exit 0
        git push
